"""create all seven domain tables

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-27

Handwritten (non-autogenerated) so the single initial migration is reviewable
and additive-only. Column types mirror the SQLAlchemy 2.0 models in
``app/modules/*/models.py``: Python enums are stored as VARCHAR (SQLite has
no native enum), decimals as NUMERIC, timestamps as naive-UTC DATETIME.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. users (no dependencies)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("last_access_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.UniqueConstraint("username"),
    )
    op.create_index("ix_users_username", "users", ["username"])

    # 2. pantone_colors (no dependencies); code unique + indexed
    op.create_table(
        "pantone_colors",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("gamut", sa.String(), nullable=False, server_default="C"),
        sa.Column("paint_type", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.UniqueConstraint("code"),
    )
    op.create_index("ix_pantone_colors_code", "pantone_colors", ["code"])

    # 3. access_logs (FK -> users)
    op.create_table(
        "access_logs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
    )

    # 4. formulas (FK -> pantone_colors, users[created_by])
    op.create_table(
        "formulas",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "pantone_color_id",
            sa.Integer(),
            sa.ForeignKey("pantone_colors.id"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )

    # 5. formula_ingredients (FK -> formulas, cascade)
    op.create_table(
        "formula_ingredients",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "formula_id",
            sa.Integer(),
            sa.ForeignKey("formulas.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("colorant", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(10, 4), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
    )

    # 6. designs (FK -> users[created_by]); name unique
    op.create_table(
        "designs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("paint_type", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.UniqueConstraint("name"),
    )

    # 7. design_colors (FK -> designs cascade, pantone_colors); unique pair
    op.create_table(
        "design_colors",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "design_id",
            sa.Integer(),
            sa.ForeignKey("designs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "pantone_color_id",
            sa.Integer(),
            sa.ForeignKey("pantone_colors.id"),
            nullable=False,
        ),
        sa.UniqueConstraint("design_id", "pantone_color_id", name="uq_design_color"),
    )


def downgrade() -> None:
    op.drop_table("design_colors")
    op.drop_table("designs")
    op.drop_table("formula_ingredients")
    op.drop_table("formulas")
    op.drop_table("access_logs")
    op.drop_index("ix_pantone_colors_code", table_name="pantone_colors")
    op.drop_table("pantone_colors")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_table("users")
